/* soapH.h
   Generated by gSOAP 2.2.3b from JigleService-1.0.h
   Copyright (C) 2001-2003 Genivia inc.
   All Rights Reserved.
*/
#ifndef soapH_H
#define soapH_H
#include "stdsoap2.h"
#include "soapStub.h"

SOAP_FMAC1 void * SOAP_FMAC2 soap_instantiate(struct soap*, int, const char*, const char*);

#undef soap_destroy
#define soap_destroy(soap) soap_delete(soap, NULL)

SOAP_FMAC1 void SOAP_FMAC2 soap_delete(struct soap*, void*);

SOAP_FMAC1 void* SOAP_FMAC2 soap_class_id_enter(struct soap*, const char*, void*, int, const char*, const char*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (1)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_byte(struct soap*, char *);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_byte(struct soap*, char const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC1 char * SOAP_FMAC2 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC1 char * SOAP_FMAC2 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_xsd__int
#define SOAP_TYPE_xsd__int (2)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_xsd__int(struct soap*, int *);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_xsd__int(struct soap*, int const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_xsd__int(struct soap*, int *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_xsd__int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC1 int * SOAP_FMAC2 soap_get_xsd__int(struct soap*, int *, const char*, const char*);
SOAP_FMAC1 int * SOAP_FMAC2 soap_in_xsd__int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (3)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_int(struct soap*, int *);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_int(struct soap*, int const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC1 int * SOAP_FMAC2 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC1 int * SOAP_FMAC2 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_xsd__long
#define SOAP_TYPE_xsd__long (4)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_xsd__long(struct soap*, LONG64 *);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_xsd__long(struct soap*, LONG64 const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_xsd__long(struct soap*, LONG64 *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_xsd__long(struct soap*, const char*, int, const LONG64 *, const char*);
SOAP_FMAC1 LONG64 * SOAP_FMAC2 soap_get_xsd__long(struct soap*, LONG64 *, const char*, const char*);
SOAP_FMAC1 LONG64 * SOAP_FMAC2 soap_in_xsd__long(struct soap*, const char*, LONG64 *, const char*);

#ifndef SOAP_TYPE_LONG64
#define SOAP_TYPE_LONG64 (5)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_LONG64(struct soap*, LONG64 *);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_LONG64(struct soap*, LONG64 const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_LONG64(struct soap*, LONG64 *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_LONG64(struct soap*, const char*, int, const LONG64 *, const char*);
SOAP_FMAC1 LONG64 * SOAP_FMAC2 soap_get_LONG64(struct soap*, LONG64 *, const char*, const char*);
SOAP_FMAC1 LONG64 * SOAP_FMAC2 soap_in_LONG64(struct soap*, const char*, LONG64 *, const char*);

#ifndef SOAP_TYPE_api__Filename
#define SOAP_TYPE_api__Filename (6)
#endif

SOAP_FMAC1 int SOAP_FMAC2 soap_out_api__Filename(struct soap*, const char*, int, const api__Filename *, const char*);
SOAP_FMAC1 api__Filename * SOAP_FMAC2 soap_get_api__Filename(struct soap*, api__Filename *, const char*, const char*);
SOAP_FMAC1 api__Filename * SOAP_FMAC2 soap_in_api__Filename(struct soap*, const char*, api__Filename *, const char*);

#define soap_new_api__Filename(soap, n) soap_instantiate_api__Filename(soap, n, NULL, NULL)

#define soap_delete_api__Filename(soap, p) soap_delete(soap, p)

SOAP_FMAC1 api__Filename * SOAP_FMAC2 soap_instantiate_api__Filename(struct soap*, int, const char*, const char*);

#ifndef SOAP_TYPE_api__searchResponse
#define SOAP_TYPE_api__searchResponse (7)
#endif

SOAP_FMAC1 int SOAP_FMAC2 soap_out_api__searchResponse(struct soap*, const char*, int, const api__searchResponse *, const char*);
SOAP_FMAC1 api__searchResponse * SOAP_FMAC2 soap_get_api__searchResponse(struct soap*, api__searchResponse *, const char*, const char*);
SOAP_FMAC1 api__searchResponse * SOAP_FMAC2 soap_in_api__searchResponse(struct soap*, const char*, api__searchResponse *, const char*);

#define soap_new_api__searchResponse(soap, n) soap_instantiate_api__searchResponse(soap, n, NULL, NULL)

#define soap_delete_api__searchResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 api__searchResponse * SOAP_FMAC2 soap_instantiate_api__searchResponse(struct soap*, int, const char*, const char*);

#ifndef SOAP_TYPE_api__searchFileResponse
#define SOAP_TYPE_api__searchFileResponse (8)
#endif

SOAP_FMAC1 int SOAP_FMAC2 soap_out_api__searchFileResponse(struct soap*, const char*, int, const api__searchFileResponse *, const char*);
SOAP_FMAC1 api__searchFileResponse * SOAP_FMAC2 soap_get_api__searchFileResponse(struct soap*, api__searchFileResponse *, const char*, const char*);
SOAP_FMAC1 api__searchFileResponse * SOAP_FMAC2 soap_in_api__searchFileResponse(struct soap*, const char*, api__searchFileResponse *, const char*);

#define soap_new_api__searchFileResponse(soap, n) soap_instantiate_api__searchFileResponse(soap, n, NULL, NULL)

#define soap_delete_api__searchFileResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 api__searchFileResponse * SOAP_FMAC2 soap_instantiate_api__searchFileResponse(struct soap*, int, const char*, const char*);

#ifndef SOAP_TYPE_FileArray
#define SOAP_TYPE_FileArray (9)
#endif
SOAP_FMAC1 int SOAP_FMAC2 soap_out_FileArray(struct soap*, const char*, int, const FileArray *, const char*);
SOAP_FMAC1 FileArray * SOAP_FMAC2 soap_get_FileArray(struct soap*, FileArray *, const char*, const char*);
SOAP_FMAC1 FileArray * SOAP_FMAC2 soap_in_FileArray(struct soap*, const char*, FileArray *, const char*);

#define soap_new_FileArray(soap, n) soap_instantiate_FileArray(soap, n, NULL, NULL)

#define soap_delete_FileArray(soap, p) soap_delete(soap, p)

SOAP_FMAC1 FileArray * SOAP_FMAC2 soap_instantiate_FileArray(struct soap*, int, const char*, const char*);

#ifndef SOAP_TYPE_api__SearchResult
#define SOAP_TYPE_api__SearchResult (10)
#endif

SOAP_FMAC1 int SOAP_FMAC2 soap_out_api__SearchResult(struct soap*, const char*, int, const api__SearchResult *, const char*);
SOAP_FMAC1 api__SearchResult * SOAP_FMAC2 soap_get_api__SearchResult(struct soap*, api__SearchResult *, const char*, const char*);
SOAP_FMAC1 api__SearchResult * SOAP_FMAC2 soap_in_api__SearchResult(struct soap*, const char*, api__SearchResult *, const char*);

#define soap_new_api__SearchResult(soap, n) soap_instantiate_api__SearchResult(soap, n, NULL, NULL)

#define soap_delete_api__SearchResult(soap, p) soap_delete(soap, p)

SOAP_FMAC1 api__SearchResult * SOAP_FMAC2 soap_instantiate_api__SearchResult(struct soap*, int, const char*, const char*);

#ifndef SOAP_TYPE_StringArray
#define SOAP_TYPE_StringArray (11)
#endif
SOAP_FMAC1 int SOAP_FMAC2 soap_out_StringArray(struct soap*, const char*, int, const StringArray *, const char*);
SOAP_FMAC1 StringArray * SOAP_FMAC2 soap_get_StringArray(struct soap*, StringArray *, const char*, const char*);
SOAP_FMAC1 StringArray * SOAP_FMAC2 soap_in_StringArray(struct soap*, const char*, StringArray *, const char*);

#define soap_new_StringArray(soap, n) soap_instantiate_StringArray(soap, n, NULL, NULL)

#define soap_delete_StringArray(soap, p) soap_delete(soap, p)

SOAP_FMAC1 StringArray * SOAP_FMAC2 soap_instantiate_StringArray(struct soap*, int, const char*, const char*);

#ifndef SOAP_TYPE_FilenameArray
#define SOAP_TYPE_FilenameArray (12)
#endif
SOAP_FMAC1 int SOAP_FMAC2 soap_out_FilenameArray(struct soap*, const char*, int, const FilenameArray *, const char*);
SOAP_FMAC1 FilenameArray * SOAP_FMAC2 soap_get_FilenameArray(struct soap*, FilenameArray *, const char*, const char*);
SOAP_FMAC1 FilenameArray * SOAP_FMAC2 soap_in_FilenameArray(struct soap*, const char*, FilenameArray *, const char*);

#define soap_new_FilenameArray(soap, n) soap_instantiate_FilenameArray(soap, n, NULL, NULL)

#define soap_delete_FilenameArray(soap, p) soap_delete(soap, p)

SOAP_FMAC1 FilenameArray * SOAP_FMAC2 soap_instantiate_FilenameArray(struct soap*, int, const char*, const char*);

#ifndef SOAP_TYPE_api__File
#define SOAP_TYPE_api__File (13)
#endif

SOAP_FMAC1 int SOAP_FMAC2 soap_out_api__File(struct soap*, const char*, int, const api__File *, const char*);
SOAP_FMAC1 api__File * SOAP_FMAC2 soap_get_api__File(struct soap*, api__File *, const char*, const char*);
SOAP_FMAC1 api__File * SOAP_FMAC2 soap_in_api__File(struct soap*, const char*, api__File *, const char*);

#define soap_new_api__File(soap, n) soap_instantiate_api__File(soap, n, NULL, NULL)

#define soap_delete_api__File(soap, p) soap_delete(soap, p)

SOAP_FMAC1 api__File * SOAP_FMAC2 soap_instantiate_api__File(struct soap*, int, const char*, const char*);

#ifndef SOAP_TYPE_api__versionResponse
#define SOAP_TYPE_api__versionResponse (14)
#endif

SOAP_FMAC1 int SOAP_FMAC2 soap_out_api__versionResponse(struct soap*, const char*, int, const api__versionResponse *, const char*);
SOAP_FMAC1 api__versionResponse * SOAP_FMAC2 soap_get_api__versionResponse(struct soap*, api__versionResponse *, const char*, const char*);
SOAP_FMAC1 api__versionResponse * SOAP_FMAC2 soap_in_api__versionResponse(struct soap*, const char*, api__versionResponse *, const char*);

#define soap_new_api__versionResponse(soap, n) soap_instantiate_api__versionResponse(soap, n, NULL, NULL)

#define soap_delete_api__versionResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 api__versionResponse * SOAP_FMAC2 soap_instantiate_api__versionResponse(struct soap*, int, const char*, const char*);

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (15)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (16)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (17)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#ifndef SOAP_TYPE_api__search
#define SOAP_TYPE_api__search (18)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_api__search(struct soap*, struct api__search const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_api__search(struct soap*, const struct api__search *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_api__search(struct soap*, struct api__search *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_api__search(struct soap*, struct api__search *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_api__search(struct soap*, const char*, int, const struct api__search *, const char*);
SOAP_FMAC1 struct api__search * SOAP_FMAC2 soap_get_api__search(struct soap*, struct api__search *, const char*, const char*);
SOAP_FMAC1 struct api__search * SOAP_FMAC2 soap_in_api__search(struct soap*, const char*, struct api__search *, const char*);

#ifndef SOAP_TYPE_api__searchFile
#define SOAP_TYPE_api__searchFile (19)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_api__searchFile(struct soap*, struct api__searchFile const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_api__searchFile(struct soap*, const struct api__searchFile *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_api__searchFile(struct soap*, struct api__searchFile *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_api__searchFile(struct soap*, struct api__searchFile *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_api__searchFile(struct soap*, const char*, int, const struct api__searchFile *, const char*);
SOAP_FMAC1 struct api__searchFile * SOAP_FMAC2 soap_get_api__searchFile(struct soap*, struct api__searchFile *, const char*, const char*);
SOAP_FMAC1 struct api__searchFile * SOAP_FMAC2 soap_in_api__searchFile(struct soap*, const char*, struct api__searchFile *, const char*);

#ifndef SOAP_TYPE_api__version
#define SOAP_TYPE_api__version (20)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_api__version(struct soap*, struct api__version const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_api__version(struct soap*, const struct api__version *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_api__version(struct soap*, struct api__version *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_api__version(struct soap*, struct api__version *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_api__version(struct soap*, const char*, int, const struct api__version *, const char*);
SOAP_FMAC1 struct api__version * SOAP_FMAC2 soap_get_api__version(struct soap*, struct api__version *, const char*, const char*);
SOAP_FMAC1 struct api__version * SOAP_FMAC2 soap_in_api__version(struct soap*, const char*, struct api__version *, const char*);

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (21)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC1 struct SOAP_ENV__Code ** SOAP_FMAC2 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC1 struct SOAP_ENV__Code ** SOAP_FMAC2 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#ifndef SOAP_TYPE_PointerToapi__searchResponse
#define SOAP_TYPE_PointerToapi__searchResponse (22)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerToapi__searchResponse(struct soap*, api__searchResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerToapi__searchResponse(struct soap*, api__searchResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerToapi__searchResponse(struct soap*, api__searchResponse **);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_PointerToapi__searchResponse(struct soap*, api__searchResponse **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_PointerToapi__searchResponse(struct soap*, const char *, int, api__searchResponse *const*, const char *);
SOAP_FMAC1 api__searchResponse ** SOAP_FMAC2 soap_get_PointerToapi__searchResponse(struct soap*, api__searchResponse **, const char*, const char*);
SOAP_FMAC1 api__searchResponse ** SOAP_FMAC2 soap_in_PointerToapi__searchResponse(struct soap*, const char*, api__searchResponse **, const char*);

#ifndef SOAP_TYPE_PointerToapi__searchFileResponse
#define SOAP_TYPE_PointerToapi__searchFileResponse (23)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerToapi__searchFileResponse(struct soap*, api__searchFileResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerToapi__searchFileResponse(struct soap*, api__searchFileResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerToapi__searchFileResponse(struct soap*, api__searchFileResponse **);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_PointerToapi__searchFileResponse(struct soap*, api__searchFileResponse **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_PointerToapi__searchFileResponse(struct soap*, const char *, int, api__searchFileResponse *const*, const char *);
SOAP_FMAC1 api__searchFileResponse ** SOAP_FMAC2 soap_get_PointerToapi__searchFileResponse(struct soap*, api__searchFileResponse **, const char*, const char*);
SOAP_FMAC1 api__searchFileResponse ** SOAP_FMAC2 soap_in_PointerToapi__searchFileResponse(struct soap*, const char*, api__searchFileResponse **, const char*);

#ifndef SOAP_TYPE_PointerToapi__versionResponse
#define SOAP_TYPE_PointerToapi__versionResponse (24)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerToapi__versionResponse(struct soap*, api__versionResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerToapi__versionResponse(struct soap*, api__versionResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerToapi__versionResponse(struct soap*, api__versionResponse **);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_PointerToapi__versionResponse(struct soap*, api__versionResponse **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_PointerToapi__versionResponse(struct soap*, const char *, int, api__versionResponse *const*, const char *);
SOAP_FMAC1 api__versionResponse ** SOAP_FMAC2 soap_get_PointerToapi__versionResponse(struct soap*, api__versionResponse **, const char*, const char*);
SOAP_FMAC1 api__versionResponse ** SOAP_FMAC2 soap_in_PointerToapi__versionResponse(struct soap*, const char*, api__versionResponse **, const char*);

#ifndef SOAP_TYPE_PointerToapi__Filename
#define SOAP_TYPE_PointerToapi__Filename (25)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerToapi__Filename(struct soap*, api__Filename *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerToapi__Filename(struct soap*, api__Filename *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerToapi__Filename(struct soap*, api__Filename **);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_PointerToapi__Filename(struct soap*, api__Filename **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_PointerToapi__Filename(struct soap*, const char *, int, api__Filename *const*, const char *);
SOAP_FMAC1 api__Filename ** SOAP_FMAC2 soap_get_PointerToapi__Filename(struct soap*, api__Filename **, const char*, const char*);
SOAP_FMAC1 api__Filename ** SOAP_FMAC2 soap_in_PointerToapi__Filename(struct soap*, const char*, api__Filename **, const char*);

#ifndef SOAP_TYPE_PointerToapi__SearchResult
#define SOAP_TYPE_PointerToapi__SearchResult (26)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerToapi__SearchResult(struct soap*, api__SearchResult *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerToapi__SearchResult(struct soap*, api__SearchResult *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerToapi__SearchResult(struct soap*, api__SearchResult **);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_PointerToapi__SearchResult(struct soap*, api__SearchResult **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_PointerToapi__SearchResult(struct soap*, const char *, int, api__SearchResult *const*, const char *);
SOAP_FMAC1 api__SearchResult ** SOAP_FMAC2 soap_get_PointerToapi__SearchResult(struct soap*, api__SearchResult **, const char*, const char*);
SOAP_FMAC1 api__SearchResult ** SOAP_FMAC2 soap_in_PointerToapi__SearchResult(struct soap*, const char*, api__SearchResult **, const char*);

#ifndef SOAP_TYPE_PointerToapi__File
#define SOAP_TYPE_PointerToapi__File (27)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerToapi__File(struct soap*, api__File *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerToapi__File(struct soap*, api__File *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerToapi__File(struct soap*, api__File **);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_PointerToapi__File(struct soap*, api__File **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_PointerToapi__File(struct soap*, const char *, int, api__File *const*, const char *);
SOAP_FMAC1 api__File ** SOAP_FMAC2 soap_get_PointerToapi__File(struct soap*, api__File **, const char*, const char*);
SOAP_FMAC1 api__File ** SOAP_FMAC2 soap_in_PointerToapi__File(struct soap*, const char*, api__File **, const char*);

#ifndef SOAP_TYPE_PointerToFileArray
#define SOAP_TYPE_PointerToFileArray (28)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerToFileArray(struct soap*, FileArray *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerToFileArray(struct soap*, FileArray *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerToFileArray(struct soap*, FileArray **);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_PointerToFileArray(struct soap*, FileArray **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_PointerToFileArray(struct soap*, const char *, int, FileArray *const*, const char *);
SOAP_FMAC1 FileArray ** SOAP_FMAC2 soap_get_PointerToFileArray(struct soap*, FileArray **, const char*, const char*);
SOAP_FMAC1 FileArray ** SOAP_FMAC2 soap_in_PointerToFileArray(struct soap*, const char*, FileArray **, const char*);

#ifndef SOAP_TYPE_PointerToxsd__string
#define SOAP_TYPE_PointerToxsd__string (29)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerToxsd__string(struct soap*, char **const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerToxsd__string(struct soap*, char **const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerToxsd__string(struct soap*, char ***);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_PointerToxsd__string(struct soap*, char ***, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_PointerToxsd__string(struct soap*, const char *, int, char **const*, const char *);
SOAP_FMAC1 char *** SOAP_FMAC2 soap_get_PointerToxsd__string(struct soap*, char ***, const char*, const char*);
SOAP_FMAC1 char *** SOAP_FMAC2 soap_in_PointerToxsd__string(struct soap*, const char*, char ***, const char*);

#ifndef SOAP_TYPE_PointerToStringArray
#define SOAP_TYPE_PointerToStringArray (30)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerToStringArray(struct soap*, StringArray *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerToStringArray(struct soap*, StringArray *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerToStringArray(struct soap*, StringArray **);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_PointerToStringArray(struct soap*, StringArray **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_PointerToStringArray(struct soap*, const char *, int, StringArray *const*, const char *);
SOAP_FMAC1 StringArray ** SOAP_FMAC2 soap_get_PointerToStringArray(struct soap*, StringArray **, const char*, const char*);
SOAP_FMAC1 StringArray ** SOAP_FMAC2 soap_in_PointerToStringArray(struct soap*, const char*, StringArray **, const char*);

#ifndef SOAP_TYPE_PointerToFilenameArray
#define SOAP_TYPE_PointerToFilenameArray (31)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerToFilenameArray(struct soap*, FilenameArray *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerToFilenameArray(struct soap*, FilenameArray *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerToFilenameArray(struct soap*, FilenameArray **);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_PointerToFilenameArray(struct soap*, FilenameArray **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_PointerToFilenameArray(struct soap*, const char *, int, FilenameArray *const*, const char *);
SOAP_FMAC1 FilenameArray ** SOAP_FMAC2 soap_get_PointerToFilenameArray(struct soap*, FilenameArray **, const char*, const char*);
SOAP_FMAC1 FilenameArray ** SOAP_FMAC2 soap_in_PointerToFilenameArray(struct soap*, const char*, FilenameArray **, const char*);

#ifndef SOAP_TYPE_xsd__string
#define SOAP_TYPE_xsd__string (32)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_xsd__string(struct soap*, char **);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_xsd__string(struct soap*, char *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_xsd__string(struct soap*, char *const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_xsd__string(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_xsd__string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC1 char ** SOAP_FMAC2 soap_get_xsd__string(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 char * * SOAP_FMAC2 soap_in_xsd__string(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (33)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_string(struct soap*, char **);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_string(struct soap*, char *const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC1 char ** SOAP_FMAC2 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 char * * SOAP_FMAC2 soap_in_string(struct soap*, const char*, char **, const char*);
#endif

/* end of soapH.h */
